#!/bin/sh

t="$(file --dereference --brief --mime-type -- "$1")"
case "$t" in
    text/* | */xml | */json) bat -pp --terminal-width "$4" -f "$1" ;;
    application/zip) unzip -l "$1" ;;
    application/x-xz) tar -tf "$1" ;;
    application/gzip) gunzip -l "$1" ;;
    application/*-executable) rabin2 -I "$1";
                              printf "\n\n"
                              ldd 2>&1 "$1"
                              ;;
    *) echo "$t"
esac
exit 1
