#!/bin/bash

case $BLOCK_BUTTON in
	1) auddiomanager pause ;;
	4) audiomanager next ;;
	5) audiomanager prev ;;
esac

title=$(playerctl metadata title 2>/dev/null)
artist=$(playerctl metadata artist 2>/dev/null)
# album=$(playerctl metadata album 2>/dev/null)

case $(playerctl status 2>/dev/null) in
	"Playing") echo "$artist - $title" ;;
	"Paused") echo "<span color=\"gray\" font_style=\"italic\">$artist - $title</span>" ;;
esac

