#!/bin/bash

case $BLOCK_BUTTON in
	1) audiomanager mute ;;
	4) audiomanager up 5 ;;
	5) audiomanager down 5 ;;
esac

muted=$(pactl list sinks | grep "Mute: " | head "-$(($ACTIVE_SINK + 1))" | awk "{print \$2}")
volume=$(pactl list sinks | grep "Volume: f" | head "-$(($ACTIVE_SINK + 1))" | awk "{print \$5}")

if [ "$muted" == "yes" ] || [ "$volume" == "0%" ];
then
	echo ""
else
	if [ "${volume::-1}" -gt "40" ];
	then
		echo " $volume"
	else
		echo " $volume"
	fi
fi

